core:
  defaultRuleSyntax: v2

deployment:
  podAnnotations:
    linkerd.io/inject: ingress
    config.alpha.linkerd.io/proxy-enable-native-sidecar: "true"

experimental:
  kubernetesGateway:
    enabled: true

providers:
  kubernetesCRD:
    enabled: false
  kubernetesIngress:
    enabled: false
  kubernetesGateway:
    enabled: true
    experimentalChannel: true

ingressClass:
  enabled: false

service:
  enabled: false
