apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "gateway-api-route-controller-role"
  namespace: default
rules:
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - gateway.networking.k8s.io
    resources:
      - httproutes
      - grpcroutes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "gateway-api-route-controller-role-binding"
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "gateway-api-route-controller-role"
subjects:
  - kind: ServiceAccount
    name: "argo-rollouts"
    namespace: default